#!/bin/bash

IMAGE_NAME=cartes
IMAGE_VERSION=latest
DEFAULT_REGISTRY=hypercube.local:5000

npm run build
docker build -t $IMAGE_NAME:$IMAGE_VERSION .
docker tag $IMAGE_NAME:$IMAGE_VERSION $DEFAULT_REGISTRY/$IMAGE_NAME:$IMAGE_VERSION
docker push $DEFAULT_REGISTRY/$IMAGE_NAME:$IMAGE_VERSION
